version: "3"
services: 
  dbservice:
    image: mysql
    environment: 
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - bootcomposeapp

  springjenkinsmockservice:
    build: ./bootapp
    depends_on: 
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/employee_service?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=test
    ports:
      - 8085:8081
    networks:
      - bootcomposeapp

networks:
  bootcomposeapp:
    
