server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mokito
    username: root
    password: intelliatech
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      file-size-threshold: 1KB